name: 'cifar10_resnetv1_32'


model:
  name: vel.model.vision.cifar_resnet_v1
  img_channels: 3
  num_classes: 10

  mode: basic # Basic or bottleneck
  blocks: [5, 5, 5] # ResNet32


source:
  name: vel.data.source.vision.cifar10


loader:
  name: vel.data.loader.dataset_loader
  batch_size: 128
  num_workers: 4

  transformations:
    - name: vel.data.transformation.to_array
    - name: vel.data.transformation.normalize
    - name: vel.data.augmentation.random_crop
      tags: ["train"]
      width: 32
      height: 32
      padding: 4
      padding_mode: 'reflect'
    - name: vel.data.augmentation.random_horizontal_flip
      tags: ["train"]
    - name: vel.data.transformation.image_to_tensor


optimizer:
  name: vel.optimizer.sgd
  lr: 0.1
  weight_decay: 0.0001
  momentum: 0.9


scheduler:
  name: vel.scheduler.ladder
  ladder:
    - [80, 1.0]
    - [40, 0.1]
    - [80, 0.01]


commands:
  train:
    name: vel.command.train_command
    epochs: 200


  augvis:
    name: vel.command.augvis_command
    samples: 5
    cases: 3
