name: 'mnist_gan'


model:
  name: vel.model.gan.simple_gan
  img_rows: 28
  img_cols: 28
  img_channels: 1
  latent_dim: 128


source:
  name: vel.data.source.vision.mnist


loader:
  name: vel.data.dataset_loader
  batch_size: 128
#  num_workers: 4
#  pin_memory: true

  transformations:
    - name: vel.data.transformation.to_array
    #    - name: vel.data.augmentation.random_scale
    #      tags: train
    #      size: 28
    #      max_zoom: 1.1
    #    - name: vel.data.augmentation.random_rotate
    #      tags: train
    #      deg: 15.0
    #    - name: vel.data.augmentation.random_crop
    #      tags: train
    #      width: 28
    #      height: 28
    #      padding: 3
    #      padding_mode: 'constant'
    - name: vel.data.transformation.image_to_tensor
    - name: vel.data.transformation.unsupervised


optimizer:
  name: vel.optimizer.radam
  lr: 2.0e-4
  eps: 1.0e-4


#scheduler:
#  name: vel.scheduler.multi_step
#  gamma: 0.71968  # 10 * (-1/7)
#  milestones: [   1,    4,   13,   40,  121,  364, 1093, 3280]


commands:
  augvis:
    name: vel.command.augvis_command
    samples: 10
    cases: 5

  train:
    name: vel.command.train_command
    epochs: 200
