name: 'mnist_cnn_ae'


model:
  name: vel.model.autoencoder.mnist_cnn_autoencoder
  img_rows: 28
  img_cols: 28
  img_channels: 1
  channels: [8, 16, 16]
  representation_length: 16


source:
  name: vel.data.source.vision.mnist


loader:
  name: vel.data.dataset_loader
  batch_size: 128
  num_workers: 4

  transformations:
    - name: vel.data.transformation.image_to_tensor
    - name: vel.data.transformation.unsupervised


optimizer:
  name: vel.optimizer.adam
  lr: 1.0e-3


commands:
  train:
    name: vel.command.train_command
    epochs: 12
    log_frequency: 100

    checkpoint:
      metric: 'val:loss'
