name: 'omniglot_cnn_vae'


model:
  name: vel.model.latent.cnn_vae
  img_rows: 28
  img_cols: 28
  img_channels: 1
  channels: [64, 128, 256]
  representation_length: 50
  max_grad_norm: 1.0
  analytical_kl_div: true


source:
  name: vel.data.source.vision.omniglot


loader:
  name: vel.data.loader.dataset_loader
  batch_size: 128
  num_workers: 4
  pin_memory: true

  transformations:
    - name: vel.data.transformation.pil_resize
      shape: [28, 28]
    - name: vel.data.transformation.to_array
    - name: vel.data.transformation.binarize_image
    - name: vel.data.transformation.image_to_tensor
    - name: vel.data.transformation.unsupervised


optimizer:
  name: vel.optimizer.radam
  lr: 1.0e-3
  eps: 1.0e-4


commands:
  augvis:
    name: vel.command.augvis_command
    samples: 5
    cases: 3

  train:
    name: vel.command.train_command
    epochs: 3280

