name: 'mnist_cnn_01'


model:
  name: vel.model.vision.mnist_cnn_01
  img_rows: 28
  img_cols: 28
  img_channels: 1
  num_classes: 10


source:
  name: vel.data.source.vision.mnist


loader:
  name: vel.data.loader.dataset_loader
  batch_size: 128
#  num_workers: 4

  transformations:
    - name: vel.data.transformation.image_to_tensor


optimizer:
  name: vel.optimizer.adadelta
  max_grad_norm: 1.0


commands:
  train:
    name: vel.command.train_command
    epochs: 12


  augvis:
    name: vel.command.augvis_command
    samples: 3
    cases: 3
