name: 'mnist_cnn_vq_vae'


model:
  name: vel.model.latent.vq_vae
  img_rows: 28
  img_cols: 28
  img_channels: 1
  channels: [64, 128, 256]
#  channels: [32, 64, 128]

  k: 128
  d: 64


source:
  name: vel.data.source.vision.mnist


loader:
  name: vel.data.loader.dataset_loader
  batch_size: 128
#  num_workers: 4
#  pin_memory: true

  transformations:
    - name: vel.data.transformation.to_array
    - name: vel.data.transformation.image_to_tensor
    - name: vel.data.transformation.unsupervised


optimizer:
  name: vel.optimizer.radam
  lr: 1.0e-3
  eps: 1.0e-4


scheduler:
  name: vel.scheduler.multi_step
  gamma: 0.71968  # 10 * (-1/7)
  milestones: [   1,    4,   13,   40,  121,  364, 1093, 3280]


commands:
  augvis:
    name: vel.command.augvis_command
    samples: 10
    cases: 5

  train:
    name: vel.command.train_command
#    epochs: 3280
    epochs: 50
