name: 'atari_a2c_lstm'


env:
  name: vel.rl.env.classic_atari
  game: !param game = 'BreakoutNoFrameskip-v4'


vec_env:
  name: vel.rl.vecenv.shared_mem
  frame_history: 1  # How many stacked frames go into a single observation


model:
  name: vel.rl.policy.a2c_rnn

  entropy_coefficient: 0.01
  value_coefficient: 0.5
  discount_factor: 0.99

  net:
    name: vel.net.modular
    layers:
      - name: vel.net.layer.input.image_to_tensor
      - name: vel.rl.layer.nature_cnn
      - name: vel.rl.layer.rnn_cell
        hidden_size: 512
        rnn_type: 'lstm'
      - name: vel.net.layer.util.repeat
        times: 2 # Need to repeat output twice, for action and value heads


reinforcer:
  name: vel.rl.reinforcer.on_policy_iteration_reinforcer

  env_roller:
    name: vel.rl.env_roller.step_env_roller

  number_of_steps: 5 # How many environment steps go into a single batch
  parallel_envs: 16 # How many environments to run in parallel

  shuffle_transitions: off  # Required for RNN policies


optimizer:
  name: vel.optimizer.rmsprop
  lr: 7.0e-4
  alpha: 0.99
  epsilon: 1.0e-3
  max_grad_norm: 0.5


commands:
  train:
    name: vel.rl.command.rl_train_command
    total_frames: 1.1e7
    batches_per_epoch: 100

  record:
    name: vel.rl.command.record_movie_command
    takes: 10
    videoname: 'atari_vid_{:04}.avi'

  evaluate:
    name: vel.rl.command.evaluate_env_command
    parallel_envs: 16 # How many environments to run in parallel

    takes: 20

  visdom:
    name: vel.command.vis_store_command
