name: 'atari_ppo_gru'


env:
  name: vel.rl.env.classic_atari
  game: !param game = 'BreakoutNoFrameskip-v4'


vec_env:
  name: vel.rl.vecenv.shared_mem


model:
  name: vel.rl.policy.ppo_rnn

  entropy_coefficient: 0.01
  value_coefficient: 0.5

  discount_factor: 0.99 # Discount factor for the rewards
  gae_lambda: 0.95 # Generalized Advantage Estimator Lambda parameter

  cliprange:
    name: vel.function.linear
    initial_value: 0.1
    final_value: 0.0

  net:
    name: vel.net.modular
    layers:
      - name: vel.net.layer.input.image_to_tensor
      - name: vel.rl.layer.nature_cnn
      - name: vel.rl.layer.rnn_cell
        hidden_size: 512
        rnn_type: 'gru'
      - name: vel.net.layer.util.repeat
        times: 2 # Need to repeat output twice, for action and value heads


reinforcer:
  name: vel.rl.reinforcer.on_policy_iteration_reinforcer

  env_roller:
    name: vel.rl.env_roller.step_env_roller

  parallel_envs: 8 # How many environments to run in parallel
  number_of_steps: 128 # How many environment steps go into a single batch
  batch_size: 256 # How many samples can go into the model once
  experience_replay: 4 # How many times to replay the experience

  shuffle_transitions: off  # Required for RNN policies


optimizer:
  name: vel.optimizer.adam
  lr: 2.5e-4
  epsilon: 1.0e-5
  max_grad_norm: 0.5 # Gradient clipping parameter


scheduler:
  name: vel.scheduler.linear_batch_scaler


commands:
  train:
    name: vel.rl.command.rl_train_command
    total_frames: 1.1e7
    batches_per_epoch: 10

  record:
    name: vel.rl.command.record_movie_command
    takes: 10
    videoname: 'atari_ppo_gru_vid_{:04}.avi'

  evaluate:
    name: vel.rl.command.evaluate_env_command
    parallel_envs: 16 # How many environments to run in parallel

    takes: 20
