name: 'gen_shakespeare'


source:
  name: vel.data.source.nlp.text_url
  # Andrej Karpathy built a small (4.4mb) file with combined all works of Shakespeare
  url: 'https://cs.stanford.edu/people/karpathy/char-rnn/shakespeare_input.txt'
  local_dir: './rnn_shakespeare'


loader:
  name: vel.data.text_character_loader
  sequence_length: 128
  batch_size: 64


model:
  name: vel.model.nlp.language_model

  net:
    name: vel.net.modular
    layers:
      - name: vel.net.layer.nlp.alphabet_embedding
        dim: 512
      - name: vel.net.layer.rnn
        hidden_size: 512
        rnn_type: 'lstm'
      - name: vel.net.layer.dropout
        p: 0.3
      - name: vel.net.layer.rnn
        hidden_size: 512
        rnn_type: 'lstm'
        dropout: 0.5
      - name: vel.net.layer.dropout
        p: 0.3
      - name: vel.net.layer.rnn
        hidden_size: 512
        rnn_type: 'lstm'
        dropout: 0.5
      - name: vel.net.layer.dropout
        p: 0.3


optimizer:
  name: vel.optimizer.adam
  lr: 1.0e-3
  epsilon: 1.0e-5


commands:
  train:
    name: vel.command.train_command
    max_grad_norm: 0.5
    epochs: 20

  generate:
    name: vel.command.rnn.generate_text
    start_letter: !param start_letter = 'A'
    length: !param length = 500
    temperature: !param temperature = 0.8


