name: 'mujoco_ppo'


env:
  name: vel.rl.env.mujoco
  game: !param game = 'Reacher-v2'


vec_env:
  name: vel.rl.vecenv.dummy
  normalize_returns: true


model:
  name: vel.rl.policy.ppo

  entropy_coefficient: 0.0
  value_coefficient: 0.5

  cliprange: 0.2

  discount_factor: 0.99 # Discount factor for the rewards
  gae_lambda: 0.95 # Generalized Advantage Estimator Lambda parameter

  net:
    name: vel.net.modular
    layers:
      - name: vel.net.layer.input.normalize
        shape: 11
      - name: vel.net.layer.util.repeat_tensor
        times: 2 # Need to repeat output twice, to consume by the 'parallel' layers
      - name: vel.net.layer.arch.parallel
        layers:
          - name: vel.net.layer.mlp
            hidden_layers: [64, 64]
            activation: 'tanh'
          - name: vel.net.layer.mlp
            hidden_layers: [64, 64]
            activation: 'tanh'


reinforcer:
  name: vel.rl.reinforcer.on_policy_iteration_reinforcer

  env_roller:
    name: vel.rl.env_roller.step_env_roller

  parallel_envs: 1 # How many environments to run in parallel
  batch_size: 64 # How many samples can go into the model in one batch
  number_of_steps: 2048 # How many environment steps go into a single batch
  experience_replay: 10 # How many times to replay the experience


optimizer:
  name: vel.optimizer.adam
  lr: 3.0e-4
  epsilon: 1.0e-5
  max_grad_norm: 0.5 # Gradient clipping parameter


scheduler:
  name: vel.scheduler.linear_batch_scaler


commands:
  train:
    name: vel.rl.command.rl_train_command
    total_frames: 1.0e6
    batches_per_epoch: 1

  record:
    name: vel.rl.command.record_movie_command
    takes: 10
    videoname: 'half_cheetah_vid_{:04}.avi'
